---

- hosts: all
  become: yes

  tasks:
    - name: Prepare environment
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Clone git repo
      git:
        repo: https://github.com/HerbyDE/GloFed.git
        dest: ~/repos/GloFed
        clone: yes
        update: yes
      become_user: ubuntu

    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Setup virtualenv
      shell: python3 -m venv ~/virt_env
      become_user: ubuntu

    - name: Install python requirements to virtual environment
      pip:
        requirements: ~/repos/GloFed/requirements.txt
        virtualenv: ~/virt_env
        virtualenv_site_packages: yes
        virtualenv_python: python3

    - name: Launch Federated Learning client
      script: ~/fedglove/main.py


