---

- hosts: all
  become_user: ubuntu

  tasks:
    - name: Prepare environment
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Clone git repo
      git:
        repo: https://github.com/HerbyDE/GloFed.git
        dest: ~/repos/GloFed
        clone: yes
        update: yes

    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Setup virtualenv
      shell: python3 -m venv ~/virt_env

    - name: Install python requirements to virtual environment
      pip:
        requirements: ~/repos/GloFed/requirements.txt
        virtualenv: ~/virt_env
        virtualenv_command: virtualenv
        virtualenv_site_packages: no
        virtualenv_python: 3.8.10


