---

- hosts: all
  become: yes

  tasks:
    - name: Prepare environment
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install GitLab SSH Key
      copy:
        src: /home/woi/.ssh/id_rsa
        dest: ~/.ssh/
      become: yes

    - name: Install GitLab SSH Key
      copy:
        src: /home/woi/.ssh/id_rsa.pub
        dest: ~/.ssh/
      become: yes

    - name: Clone git repo
      git:
        repo: git@gitlab.i13.in.tum.de:woi/fedglove.git
        dest: ~/repos/
        clone: yes
        update: yes
        key_file: ~/.ssh/id_rsa
        accept_hostkey: yes
        force: yes

    - name: Remove SSH keys from client
      file:
        path: "{{ item  }}"
      loop:
        - /home/woi/.ssh/id_rsa
        - /home/woi/.ssh/id_rsa.pub

    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Setup virtualenv
      shell: virtualenv venv

    - name: Install python requirements to virtual environment
      pip:
        requirements: ~/fedglove/requirements.txt
        virtualenv: ~/venv
        virtualenv_site_packages: yes
        virtualenv_python: python3

    - name: Launch Federated Learning client
      script: ~/fedglove/main.py


